apiVersion: v1
kind: ServiceAccount
metadata:
  name: easypay-admin
  namespace: infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager
  namespace: infra
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","get","list","watch","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager-binding
  namespace: infra
subjects:
- kind: ServiceAccount
  name: easypay-admin
  namespace: infra
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
